name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:  # 新增：监听 Repository Dispatch 事件
    types: [blog-post-updated]  # 匹配子模块仓库的 event-type
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install
      - name: Fetch Posts
        env:
          POST_REPO: ${{ secrets.POST_REPO }}
          POST_BRANCH: ${{ secrets.POST_BRANCH }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: yarn fetch-posts
      - name: Check if Vercel Token exists
        id: check-vercel-token
        run: |
          if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "has_vercel_token=true" >> $GITHUB_OUTPUT
          else
            echo "has_vercel_token=false" >> $GITHUB_OUTPUT
          fi
      - name: Install Vercel CLI
        if: steps.check-vercel-token.outputs.has_vercel_token == 'true'
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        if: steps.check-vercel-token.outputs.has_vercel_token == 'true'
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        if: steps.check-vercel-token.outputs.has_vercel_token == 'true'
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        if: steps.check-vercel-token.outputs.has_vercel_token == 'true'
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}